### ISSUE TITLE
Cannot create new project: FSharp.Core not found

### ISSUE THREAD

**Issue by jeroldhaas** [intellifactory/monodevelop.websharper#14]
```
System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at WebSharper.Templates.InitOptions.Create(String directory, String projectName, Byte[] templatesPackage)
   at MonoDevelop.WebSharper.ProjectUtility.createProject(Setup _arg1)
   at MonoDevelop.WebSharper.ProjectUtility.BaseProjectBinding.CreateProject(String lang, ProjectCreateInformation info, XmlElement opts)
   at MonoDevelop.Projects.DotNetProjectBinding.CreateProject(ProjectCreateInformation info, XmlElement projectOptions)
   at MonoDevelop.Projects.ProjectService.CreateProject(String type, ProjectCreateInformation info, XmlElement projectOptions)
   at MonoDevelop.Ide.Templates.ProjectDescriptor.CreateItem(ProjectCreateInformation projectCreateInformation, String defaultLanguage)
   at MonoDevelop.Ide.Templates.SolutionDescriptor.CreateEntry(ProjectCreateInformation projectCreateInformation, String defaultLanguage)
   at MonoDevelop.Ide.Templates.ProjectTemplate.CreateWorkspaceItem(ProjectCreateInformation cInfo)
   at MonoDevelop.Ide.Templates.ProjectTemplatingProvider.ProcessTemplate(DefaultSolutionTemplate template, NewProjectConfiguration config, SolutionFolder parentFolder)
   at MonoDevelop.Ide.Templates.ProjectTemplatingProvider.ProcessTemplate(SolutionTemplate template, NewProjectConfiguration config, SolutionFolder parentFolder)
   at MonoDevelop.Ide.Templates.TemplatingService.ProcessTemplate(SolutionTemplate template, NewProjectConfiguration config, SolutionFolder parentFolder)
   at MonoDevelop.Ide.Projects.NewProjectDialogController.CreateProject()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by granicz** [comment]
What installer do you have?

**Comment by jeroldhaas** [comment]
I'm not sure I understand the question. The add-in was installed through XS's add-in manager. 

Additional relevant info:
```
Xamarin Studio
Version 5.9.7 (build 22)
Installation UUID: 1372b4e9-7fdf-4ea6-9693-f18f50ad46d9
Runtime:
	Microsoft .NET 4.0.30319.42000
	GTK+ 2.24.22 (MS-Windows theme)
	GTK# 2.12.26

Xamarin.Android
Version: 5.1.7 (Enterprise Edition)
Android SDK: C:\Users\jhaas\AppData\Local\Android\android-sdk
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
Java SDK: C:\Program Files (x86)\Java\jdk1.7.0_75
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) Client VM (build 24.75-b04, mixed mode, sharing)

Xamarin Android Player
Version: 0.6.2
Location: C:\Program Files\Xamarin Android Player\DeviceManager.exe

Build Information
Release ID: 509070022
Git revision: 6bd1f169df44ca96addf8a035316c535a4fa46fa
Build date: 2015-09-30 10:13:51-04
Xamarin addins: 1c3e5c0859bdfec0ecd481a57ad6c03bc22f5536

Operating System
Windows 6.2.9200.0 (64-bit)
```

**Comment by granicz** [comment]
Hold on - a new package is on its way, I think we found the issue.

**Comment by Tarmil** [comment]
A fixed package is built, it's now awaiting publication on the Xamarin channel.

**Comment by jeroldhaas** [comment]
Project is now building from template. Confirmed fix. Thanks! :+1:
